// Poses, one grid each, drawn upright with the head at the top. The painter
// rotates the whole grid so the body lines up with the web, so each of these
// only ever needs drawing once, facing one way.
//
// `neutral` is not hand drawn. It is a pixel exact trace of the reference art,
// produced by tools/trace-sprite.js, which decodes the image, works out how
// many screen pixels one art pixel became, and samples the centre of every
// cell. Copying pixel art by eye does not work, so it was not copied by eye.
//
// Grids do not all have to be the same size. Each one carries its own
// dimensions, where the centre of mass sits inside it, and which cell is the
// web wrist.

// Sampled straight out of the reference rather than chosen.
export const COLOURS = {
  a: '#020000', // outline
  b: '#d2332f', // suit red
  c: '#b91c18', // red in shadow
  d: '#1465c0', // suit blue
  e: '#0a48a3', // blue in shadow
  f: '#22247c', // deepest blue
  g: '#fdfcff', // eye white
  h: '#adadad', // eye shading
};

// Traced from the reference, 21 wide by 42 tall, not one pixel off.
const perch = [
  '.......aaaaa.........',
  '......aacbbcaa.......',
  '.....acbbbbbbca......',
  '.....accccbbbbca.....',
  '....accacccbbbba.....',
  '....accaaacbbbbba....',
  '....accaghabbbbba....',
  '....accagghabbbba....',
  '....accahhhgaabca....',
  '....aacaahggabbaa....',
  '.....acccaaabbba.....',
  '.....accccbbbbba.....',
  '......aaccbbbbca.....',
  '.......accbbbba......',
  '.......acccbba.......',
  '.....aaacccaaa.......',
  '...aabbcccbbbcaa.....',
  '..abbbbbbbbababca....',
  '..abbbbbbbbbabbca....',
  '..abeeddbbbbabbaa....',
  '.abbdadddbbababaa....',
  '.acddaafddbbbbaea....',
  '.acdaaaafddbbbaeah...',
  'abdda...addbbbaffa...',
  'abfa....affbbbafca...',
  'abbac..cffffbbbaccc..',
  'abbcca.aedddeefaccaa.',
  'abbbbcadddddddeeacbba',
  'acbbbaadddddeeeeacbaa',
  '.aabcaadedaaaeeeacca.',
  '...aa.aeedaaefeeaaa..',
  '.....aefda.affeea....',
  '.....adea..aaeea.....',
  '.....adda..aaeea.....',
  '....abdda..aeeea.....',
  '....acba...acca......',
  '....acca...acca......',
  '....aba....acca......',
  '...aaba....acca......',
  '...acba....accbaa....',
  '..aabca....accbbba...',
  '..aaaa......aaaaa....',
];

const neutral = [
  '.................aaaaa..........',
  '...............aacbbcaa.........',
  '..............acbbbbbbca........',
  '....aaa......acbbbbcccca........',
  '...abbba.....abbbbcccacca.......',
  '...abbbba...abbbbbcaaacca.......',
  '...abbba....abbbbbahgacca.......',
  '....aabba...abbbbahggacca.......',
  '.....abbba..acbaaghhhacca.......',
  '......abba..aabbagghaacaa.......',
  '......abbba..abbbaaaccca........',
  '.......abba..abbbbbcccca........',
  '.......abbba.acbbbbccaa.........',
  '........abbba.abbbbcca..........',
  '........abbbba.abbccca..........',
  '........abbbba.aaacccaaa........',
  '.........abbbbacbbbcccbbaa......',
  '.........abbbbbababbbbbbbba.....',
  '..........abbbbbabbbbbbbbba.....',
  '...........abbbbabbbbddeeba.....',
  '...........abbbbbabbdddadbba....',
  '............abbbbbbddfaaddca....',
  '.............aabbbddfaaaadca....',
  '..............abbbddaeeeaddba...',
  '..............abbbffaeeeeafba...',
  '.............abbbffffceecabba...',
  '.............afeedddeaeaccbba...',
  '............aeedddddddacbbbba...',
  '.....a.....aaeeeedddddaabbbca...',
  '....abaa.aaceaaaaaadedaacbaa....',
  '.....abaaaccceaaeaadeea.aa......',
  '.....abbccccaa..aa.aaa..........',
  '......acccaa....ada.............',
  '......aacaa....aaefa............',
  '........a.....adddea............',
  '.............aabdaa.............',
  '.............accba..............',
  '............aaccaa..............',
  '..........aabbaa................',
  '..........acca..................',
  '..........aaaa..................',
  '...........aa...................',
  '............a...................',
  '................................',
];

// Built from the traced sprite rather than drawn fresh, so the head, torso,
// palette and proportions stay exactly the reference. Only the right arm
// changes: punched up toward the anchor, with the index and pinky out and the
// middle two folded, which is the one gesture everyone recognises.
const webbing = [
  '.....................acaa....',
  '....................acaaa.aaa',
  '....................accccacaa',
  '...................aacccacaca',
  '..................aacaccaaaca',
  '...........aaaaaaaaaccccaacaa',
  '.........aaaaaaaaaccacccaacaa',
  '........aaaaacccccaecaacbbaa.',
  '.......aaacccccccccbaaabbaaa.',
  '......aaabbccbbccccacaaccca..',
  '.....aaabbbbcbbbbbabccaccaa..',
  '.....aacbbcccccccccbbbcabaa..',
  '....aaacccccccbaaaaaaaaacaa..',
  '....aaccbccbbbbaaggggaacaaa..',
  '....aaccccbbbbaaggggggabaaa..',
  '....aabccccccccaagggggacaa...',
  '....aaccccccccccagggggaaca...',
  '....accbcccccbbbaagggaaaca...',
  '.....aabbbcccbbbcaaaaaccaa...',
  '.....aacccbbccbbccbbccabaa...',
  '......aacccccccbbcbbbabcaa...',
  '.......aacbbccccacbbbabaa....',
  '........aacccccaccccbaaca....',
  '.........aaaabacbbacaaca.....',
  '..........acaccaaaaaaaa......',
  '..........aaccccaaaaaa.......',
  '.........acacaeaacccaca......',
  '.........aabceeeaccaaaa......',
  '........aaaceeaeeccaaaa......',
  '........aacceaeeecccaaa......',
  '........aacceaaeecccaaa......',
  '.......acaccaaaceacccaa......',
  '.......aaabbaaacbcbccaa......',
  '.......accccceeecbbbaa.......',
  '..aaaaaaaaccaaeeeaccaa.......',
  '.acacccaeeeaaeeeeeeeaa.......',
  'acacccaeeeeeeeeeaaeaaa.......',
  'acccccceeeeeeeaaaeeaa........',
  'caccccceeeeeacaaeeeaa........',
  'accccaaceccaaaceeeaa.........',
  'cacaaaaaaaaaaaaeeeaa.........',
  'aaaa.......aaaaaaaa..........',
  '..........acaccaaaa..........',
  '..........acaaaaaa...........',
  '..........acbbaaa............',
  '..........acabaa.............',
  '...........acca..............',
];

// Traced from the generated pose references. Each one is resampled to a grid
// by tools/trace-sprite.js and mapped onto the palette above, so every pose
// shares one set of colours no matter what the generator handed back.
const bottomSwing = [
  '...........abababa...',
  '...........abbabaa...',
  '...........aabaaaa...',
  '...........aabaaaa...',
  '........aaaabbbaa....',
  '......aaabababbaa....',
  '...aaaaaaaaacabaa....',
  '..aaaabbbbbcbbaaa....',
  '.aaabbbbbbbbcbbaba...',
  'aaabbbbbbbbcbccbaba..',
  'aabbcbbbbbbbbcbbbaa..',
  'bbbbbbbbbbaaaaaccbaa.',
  'abbbbbbbbbaaggaaccaa.',
  'abbbbbbbbbaggggaaaaaa',
  'bbbbbbbbbbaggggggabaa',
  'bbbbbbbbbbaagggggabaa',
  'abbbbbbbbbbaggggaabaa',
  'babbbbbbbbbaaaaaaccaa',
  'aabbbbbbbbbbbaaabccba',
  'abbbbbbbbbbbbbbbcacaa',
  '.aabbbbbbbbcbbcbccaa.',
  '..ababbbbbcbbcbbbaaa.',
  '...afabbcbcbcbbaaaa..',
  '....aaaababbbaafaa...',
  '.....aaabaaaaaafa....',
  '.....aabbcbbbcaaa....',
  '....aaacaaabbaaaa....',
  '....aabbfffaaaabaa...',
  '....aabcfaabbbaaaaaa.',
  '....abcaaabbbbaaaaaaa',
  '....aabcccccbbafeefaa',
  '....abbbbcbbafeeefeea',
  '.....aaabbaaffeeeeffa',
  '......aabaeffffaaeeaa',
  '......aaffeeeffafffaa',
  '......aafeffeaaabaaaa',
  '.......aaafaffaccbaaa',
  '........aaaaaabbbaaba',
  '.........aaaaaccbaaa.',
  '............aaacaaaa.',
  '.............aabaaaa.',
  '.............aabbaa..',
  '..............abaa...',
];

const upSwing = [
  '............aaaaca....',
  '...........aaacaca....',
  '...........aaaaaaaa...',
  '...........acaaaaaa...',
  '.....aaaaaaaaabaaa....',
  '....acaaaaacacbaaa....',
  '...acaaaaacbbaacaa....',
  '..aaaccacaaabcaaaa....',
  '.aacbbbabbcacaacaa....',
  'aabbbbaabbccabbbbaa...',
  'aabbbbcabbbaacbbbca...',
  'ccbbbbcccbaaaaaabbaa..',
  'ccbbbbbcbbaggggaaaaa..',
  'acbbbbbcabaggggggaaaa.',
  'acbbbbbbabaggggggaaaa.',
  'acbbbbbbabaaggggaacaa.',
  'ccbbbbbbabcaaaaaaccaa.',
  'aabbbbbcacffaaaccbbaa.',
  '.aabbbbbccffabbbacaa..',
  '..aacbbbcbafacbbccaa..',
  '..acabbbacffabbccaa...',
  '...aaaaaabafacbaaa....',
  '.....aaaacffaaaaa.....',
  '......aaaaffabaaaa....',
  '......aaaaffabbcaa....',
  '.......aafaaabbaaa....',
  '.......aaffffcbcaa....',
  '.......aaffffcccaa....',
  '.......aafffffbbaaaaa.',
  '........afffffcbcaaaaa',
  '.......acffffacaafffaa',
  '.......acaccbcffffffff',
  '........aacfffffffffff',
  '........aaaffffffaffff',
  '........acffffffaaffff',
  '.........aaffffaacaaaa',
  '..........afffffabbcaa',
  '.........aafffffbbbaa.',
  '.......aaaaffffabbbca.',
  '......aaccaffffaabaaa.',
  '.....aaccccaffaacaaca.',
  '.....aaccccaaaa.aaaa..',
  '.....accccaaaa....a...',
  '.....aaccaaa..........',
  '.....aaaaa............',
];

const downSwing = [
  '.............................................afa',
  '............................................aacc',
  '...........................................aaccc',
  '..........................................aaccaa',
  '...........................aaaaa.........aaccaaa',
  '.........................aabaaccaa......aaccacaa',
  '........................aaaaaaaaaaa....aaaccacaa',
  '.......................aaaccbccbcafa..aaccccaaa.',
  '......................aaccccbccccccaaaaacbcaaa..',
  '.....................aaacccaacccccbcaaacccaa....',
  '....................affccccaabbaacccacbccaa.....',
  '....................aabbcccaabbbbaaaccbcaa......',
  '....................afccccccabbbbbaccccaa.......',
  '....................afccccccabbbbaccffaa........',
  '....................abccccccaabbacaffaba........',
  '....................abcccccccaaaafffaafa........',
  '....................aaacccccaaafffaacaaa........',
  '....................abacccccccffffccccaa........',
  '..................aaaabacaacafffaccccca.........',
  '..............aaaaabcacaaaccfffaccccaaa.........',
  '............aabaaaaacccaffcffacbbbaaaa..........',
  '...........abaaafffffaaffaffaacaacaa............',
  '..........abaccfffffaafffaaaaaabaaa.............',
  '.........aaacccaaaaaafffaccbccca................',
  '.........aacccaaabaaffffabcccaa.................',
  '.........aaccaaabaacfffabcccaa..................',
  '..........aaaaabaaacafabbccaca..................',
  '...........aaabafffccacbbbaaa...................',
  '............abafffffcbcbcaaa....................',
  '...........afaffffffccbbafa.....................',
  '..........aaafffffffcccaaa......................',
  '.........aaaffffffffaaaa........................',
  '.......aaaffffffaaafaaa.........................',
  '.....aacaffffffafffffa..........................',
  '....abaafffffaafffaaa...........................',
  '...aaacfffffaffffaaa............................',
  '..ababbcffaafffaaa..............................',
  '.aaacbbbaaafffaaa...............................',
  'aaabcbccaaffaaa.................................',
  'fabcbbaaccaaaa..................................',
  'cbbbbaccacaa....................................',
  'cbbbaccafa......................................',
  'abcacccca.......................................',
  'caaacaaa........................................',
];

const freeFlight = [
  '.............aaccaaaaaa........',
  '............accaacaaaaaa.......',
  '...........acaccccccccaaa......',
  '..........aaacccccccccccaa.....',
  '.........aaacccccccccccccaa....',
  '........acccccccccccccccccca...',
  '........aaccccccccaacaccccca...',
  '........acccccccccaaaaaaaccaa..',
  '........aaccccccccaaggggaaaaa..',
  '........aaccccccccaaggggggacca.',
  '........aacccccccccagggggaaaca.',
  '........aacccccccccaaggggacaaa.',
  '....aaaaaaccccccccccaaaaaacaaa.',
  '.aaacaccaaaccccccccccaaaccccaa.',
  'aaaaccccccaacccccccccccccccaa..',
  'accccccfaacacccccccccccccccaa..',
  'accccaafeffcaaccccccccccccaa...',
  'accccaaafeeaccacccccccccaaaa...',
  'acaaaaaaaafffcccaaaacaaaaaa....',
  'aaaaaa..aaafffccccaacaaa.......',
  '.aaaa...aaaaffccccaaaaaa.......',
  '........aafeefcccccacaaaaa.....',
  '........aafeefccccafaccaaaaa...',
  '.......aaafeffccccfafffcccaaaa.',
  '...aaa.aaccfaacccccaaafacccaaaa',
  '..aacaaaaaccaccccaaaaafacccccca',
  'aaaaccacffaccccccaa...aacaacaaa',
  'cacccccaaefffcccaafa...aaaccaa.',
  'cccccccfaeeefffaffaca...aaacaa.',
  'acccacffffeeafffeffaca.....aa..',
  '.aaacffffeeeaffffeeefa.........',
  '....acaffefaecaaafefaa.........',
  '.....aaafaaaaaaaeeefaa.........',
  '.......aaaaaaacaeeffca.........',
  '..........acacccafaaa..........',
  '..........aaccccaaaa...........',
  '..........aaccaaaa.............',
  '..........acccaa...............',
  '...........aaaa................',
];

// `com` is where the point mass the physics simulates lands inside the drawing.
// `wrist` is where the web line ends, so it always leaves his glove.
export const POSES = {
  webbing: { grid: webbing, com: { col: 14.5, row: 29.1 }, wrist: { col: 22.5, row: 0.5 }, scaleRows: 46 },
  downSwing: { grid: downSwing, com: { col: 24, row: 27.3 }, wrist: { col: 46, row: 0.5 }, tilt: -0.65, scaleRows: 46 },
  bottomSwing: { grid: bottomSwing, com: { col: 10.5, row: 26.7 }, wrist: { col: 14, row: 0.5 }, scaleRows: 46 },
  upSwing: { grid: upSwing, com: { col: 11, row: 27.9 }, wrist: { col: 14.5, row: 0.5 }, scaleRows: 46 },
  freeFlight: { grid: freeFlight, com: { col: 15.5, row: 24.2 }, wrist: { col: 17.5, row: 0.5 }, scaleRows: 46 },
  perch: { grid: perch, com: { col: 10, row: 17.6 }, wrist: { col: 18.5, row: 28 } },
  neutral: { grid: neutral, com: { col: 16, row: 26 }, wrist: { col: 5, row: 5 } },
};
